### PR TITLE
make init a keyword argument for foldl, mapfoldl

### LINKED ISSUE #2: mapfoldl signature
In julia `1.0` init is a keyword, argument, not a positional argument. So maybe it should also be a keyword argument in the transducer case?
```julia
julia> mapfoldl(identity, =>, 1:3, init=0)
((0=>1)=>2) => 3

julia> mapfoldl(identity, =>, 0, 1:3)
ERROR: MethodError: no method matching mapfoldl(::typeof(identity), ::Type{Pair}, ::Int64, ::UnitRange{Int64})

```

### PR DESCRIPTION
**Pull request by jw3126**
fix #2

### CODE REVIEW

File: test/test_processes.jl [hunk 1]
```diff
@@ -5,25 +5,40 @@ include("preamble.jl")
...
         @test transduce(xf, push!, Int[], xs) == Reduced(1:2:19)
         @test transduce(xf, +, 0, xs) == Reduced(100)
         @test transduce(xf, +, 17, xs) == Reduced(117)
         @test transduce(xf, string, "", xs) == Reduced("135791113151719")
     end
+
+    @testset "empty" begin
+        xf = Filter(_ -> false)
+        iter = 1:4
+        @test foldl(+,xf, iter) === 0
```
Comment (tkf) [inline test/test_processes.jl]:
```suggestion
        @test foldl(+, xf, iter) === 0
```

Super minor nit, but, lets' put spaces around `,` (sorry, programming too much in Python...)

I wish we had black/gofmt for Julia.

File: test/test_processes.jl [hunk 2]
```diff
@@ -5,25 +5,40 @@ include("preamble.jl")
...
+        @test foldl(+,xf, iter, init=32.) === 32.
```
Comment (tkf) [inline test/test_processes.jl]:
```suggestion
        @test foldl(+, xf, iter, init=32.) === 32.
```

ditto

File: src/processes.jl [hunk 3]
```diff
@@ -119,8 +119,15 @@ end
 # performance for `map!` to be comparable with the native loop.
 # See: ../benchmark/bench_filter_map_map!.jl
 
-Base.mapfoldl(xform::Transducer, f, init, itr) =
-    unreduced(transduce(xform, f, init, itr))
+function mapfoldl_init(xform, step, itr)
+    T = outtype(xform, eltype(itr))
```
[the remark this answers is not in the document]
Comment (jw3126) [reply src/processes.jl]: Okay. Out of curiosity is there a specific situation that motivated `ieltype`?

File: src/processes.jl [hunk 4]
```diff
@@ -358,11 +364,19 @@ julia> foldl(Filter(isodd), 0.0, 1:4) do state, input
...
+function Base.foldl(step, xform::Transducer, itr;
+                    init=mapfoldl_init(xform, step, itr))
+    mapfoldl(xform, Completing(step), itr, init=init)
+end
 
-Base.foldl(step, ed::Eduction, init) =
-    foldl(step, Transducer(ed), init, ed.coll)
+function Base.foldl(step, ed::Eduction;
+                    init=let
+                        xf = ed.rf.xform
```
Comment (tkf) [inline src/processes.jl]: I think this actually should be `xf = Transducer(ed)` (I guess it's a bit tricky) since `ed.rf.xform` is just one "head" transducer.  Instead, we need to re-construct the chain of transducers again.  I know it is redundant but it can be fixed later.

ATM, to get the API surface right, why not just do:

```julia
Base.foldl(step, ed::Eduction; kwargs...) =
    foldl(step, Transducer(ed), ed.coll; kwargs...)
```

(Not sure how to do a multi-line suggestion in browser. Probably I need to edit locally to do that.)

File: src/processes.jl [hunk 5]
```diff
@@ -119,8 +119,15 @@ end
 # performance for `map!` to be comparable with the native loop.
 # See: ../benchmark/bench_filter_map_map!.jl
 
-Base.mapfoldl(xform::Transducer, f, init, itr) =
-    unreduced(transduce(xform, f, init, itr))
+function mapfoldl_init(xform, step, itr)
+    T = outtype(xform, ieltype(itr))
```
Comment (tkf) [inline src/processes.jl]: This actually does an `outtype`-inference twice.  I think a better place to invoke `Base.reduce_empty(step, T)` is after constructing a `Reduction` (i.e., transducers + `step`) which requires evoking `outtype` anyway.  One idea is to define a singleton `Unspecified` and pass it around as `init`:

```julia
struct Unspecified end

Base.mapfoldl(xform::Transducer, f, itr; init = Unspecified()) =
    unreduced(transduce(xform, f, init, itr))

@inline function transduce(rf::Reduction, init, coll)
    if init isa Unspecified
        # get `step` and `T` from `rf`, then...
        val = Base.reduce_empty(step, T)
    else
        val = init
    end
    return __foldl__(rf, start(rf, val), coll)
end
```

It's an optimization that can be done later.  But, if you feel like doing it, please go ahead and do it.

**Comment by tkf** [comment]
I merged it for now as it's already in a good shape.  Let me know if you want to do https://github.com/tkf/Transducers.jl/pull/3#discussion_r244515607

Thanks for the patch!
